// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ65nL28uvLA9jj2vk__0S7qdXakiXb5g',
    appId: '1:1079881177039:web:bf9fafa79bc79b1146e4ba',
    messagingSenderId: '1079881177039',
    projectId: 'otomasyon-kutuphane',
    authDomain: 'otomasyon-kutuphane.firebaseapp.com',
    storageBucket: 'otomasyon-kutuphane.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWGtoOeIncywdULGVqL42jtPQSuVLxKM4',
    appId: '1:1079881177039:android:6e8920f0060ed71446e4ba',
    messagingSenderId: '1079881177039',
    projectId: 'otomasyon-kutuphane',
    storageBucket: 'otomasyon-kutuphane.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYj67L83aqXl0NHOX1ke5KXoFArA10MDo',
    appId: '1:1079881177039:ios:087a942c85f873b146e4ba',
    messagingSenderId: '1079881177039',
    projectId: 'otomasyon-kutuphane',
    storageBucket: 'otomasyon-kutuphane.appspot.com',
    iosBundleId: 'com.example.otomasyonKutuphane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYj67L83aqXl0NHOX1ke5KXoFArA10MDo',
    appId: '1:1079881177039:ios:6232be39d706d60e46e4ba',
    messagingSenderId: '1079881177039',
    projectId: 'otomasyon-kutuphane',
    storageBucket: 'otomasyon-kutuphane.appspot.com',
    iosBundleId: 'com.example.otomasyonKutuphane.RunnerTests',
  );
}
